#!/bin/bash

yum install epel-release
yum install https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm
yum install motion ffmpeg v4l-utils mailcap python-pip python-devel gcc libcurl-devel pango-devel
pip install --upgrade pip
pip install motioneye
mkdir -p /etc/motioneye
cp /usr/share/motioneye/extra/motioneye.conf.sample /etc/motioneye/motioneye.conf
mkdir -p /var/lib/motioneye
cp /usr/share/motioneye/extra/motioneye.systemd-unit /etc/systemd/system/motioneye.service
firewall-cmd --add-port=8765/tcp --zone=public --permanent
firewall-cmd --reload
pip install motioneye --upgrade
systemctl daemon-reload
systemctl enable motioneye
systemctl start motioneye
systemctl restart motioneye
